1. Membuat array 1D dengan 5 elemen bilangan bulat acak antara 1 hingga 10:

In [2]:
import numpy as np

In [5]:
array_1d = np.random.randint(1, 11, size=5)
print("Array 1D:", array_1d)

Array 1D: [2 4 7 3 5]


2. Hitung jumlah, rata-rata, nilai minimum, dan nilai maksimum dari array yang telah dibuat.		

In [1]:
array_1d = [2, 4, 3, 7, 5]

#Menghitung jumlah
jumlah = sum(array_1d)

#hitung rata-rata
average = jumlah/len(array_1d)

#hitung nilai minimum
nilai_min = min(array_1d)

#hitung nilai max
nilai_max = max(array_1d)

#print hasil
print(f"jumlah: {jumlah}")
print(f"rata-rata: {average}")
print(f"nilai minimum: {nilai_min}")
print(f"nilai maximim: {nilai_max}")

jumlah: 21
rata-rata: 4.2
nilai minimum: 2
nilai maximim: 7


3. Buatlah dua buah array NumPy 2D dengan ukuran 3x3 yang berisi bilangan bulat acak.

In [3]:
import numpy as np

In [4]:
np.random.seed(0)

#Mengatur dua array 2d 3x3
array1 = np.random.randint(0, 10, size=(3, 3))
array2 = np.random.randint(0, 10, size=(3, 3))

#print hasil
print("array 1:")
print(array1)
print("\narray 2:")
print(array2)

array 1:
[[5 0 3]
 [3 7 9]
 [3 5 2]]

array 2:
[[4 7 6]
 [8 8 1]
 [6 7 7]]


4. Lakukan penjumlahan, pengurangan, perkalian, dan pembagian antara kedua array tersebut.	

In [6]:
#Menampilkan array 
print("array 1:")
print(array1)
print("\narray 2:")
print(array2)

#penjumlahan
penjumlahan = array1 + array2

#pengurangan
pengurangan = array1 - array2

#perkalian
perkalian = array1 * array2

#Pembagian
pembagian = np.divide(array1, array2, out=np.zeros_like(array1, dtype=float), where=array2!=0)

#tampilkan hasil operasi perhitungan
print("\nHasil penjumlahan:")
print(penjumlahan)
print("\nHasil pengurangan:")
print(pengurangan)
print("\nHasil perkalian:")
print(perkalian)
print("\nhasil pembagian")
print(pembagian)


array 1:
[[5 0 3]
 [3 7 9]
 [3 5 2]]

array 2:
[[4 7 6]
 [8 8 1]
 [6 7 7]]

Hasil penjumlahan:
[[ 9  7  9]
 [11 15 10]
 [ 9 12  9]]

Hasil pengurangan:
[[ 1 -7 -3]
 [-5 -1  8]
 [-3 -2 -5]]

Hasil perkalian:
[[20  0 18]
 [24 56  9]
 [18 35 14]]

hasil pembagian
[[1.25       0.         0.5       ]
 [0.375      0.875      9.        ]
 [0.5        0.71428571 0.28571429]]


5. Hitung determinan dari salah satu array tersebut.	

In [7]:
#Menampilkan array 1
print("array1:")
print(array1)

#Hitung determinan
determinant = np.linalg.det(array1)

#Hitung hasil
print("\n Determinan dari array 1:")
print(determinant)

array1:
[[5 0 3]
 [3 7 9]
 [3 5 2]]

 Determinan dari array 1:
-172.99999999999991


6. Buatlah array NumPy 1D dengan 10 elemen bilangan bulat dari 1 hingga 10.

In [9]:
array_1d2 = np.arange(1, 11)
print("Array 1D2:", array_1d2)

Array 1D2: [ 1  2  3  4  5  6  7  8  9 10]


7. Tampilkan elemen dengan indeks genap.	

In [15]:
#Tampilkan hasil array
array_1d2 = np.arange(1, 11)
print("Array 1D2:", array_1d2)

#menampilkan indeks genap
indeks_genap = array_1d2[::2]

#Tampilkan hasil
print("indeks genap:")
print(indeks_genap)

Array 1D2: [ 1  2  3  4  5  6  7  8  9 10]
indeks genap:
[1 3 5 7 9]


8. Ambil subset array yang hanya berisi nilai lebih dari 5.	

In [16]:
#Tampilkan hasil array
array_1d2 = np.arange(1, 11)
print("Array 1D2:", array_1d2)

#mengambil subset nilai > 5
subset = array_1d2[array_1d2 > 5]

#Tampilkan hasil
print("\nSubset yang hanya berisi nilai lebih dari 5:")
print(subset)

Array 1D2: [ 1  2  3  4  5  6  7  8  9 10]

Subset yang hanya berisi nilai lebih dari 5:
[ 6  7  8  9 10]


9.Buatlah array NumPy 2D berukuran 4x4 dengan bilangan bulat acak.9.

In [20]:
np.random.seed(0)

#Mengatur dua array 2d 4x4
array3 = np.random.randint(0, 10, size=(4, 4))

#print hasil
print("array 3:")
print(array3)

array 3:
[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]
 [8 8 1 6]]


10. Hitung nilai rata-rata, standar deviasi, median, dan korelasi antar-kolom dari array tersebut.	

In [21]:
#Tampilkan hasil
print("array 3:")
print(array3)

#nilai rata-rata
avg_array3 = np.mean(array3, axis=0)

#standar deviasi
std_dev_array3 = np.std(array3, axis=0)

#median
median_array3 = np.median(array3, axis=0)

#korelasi antar kolom dari array
correlation_array = np.corrcoef(array3, rowvar=False)


#print hasil
print("\nRata-rata per kolom:")
print(avg_array3)
print("\nStandar Deviasi per kolom:")
print(std_dev_array3)
print("\nMedian per kolom:")
print(median_array3)
print("\nMatriks Korelasi antar-kolom:")
print(correlation_array)

array 3:
[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]
 [8 8 1 6]]

Rata-rata per kolom:
[5.5  5.25 3.5  5.  ]

Standar Deviasi per kolom:
[2.29128785 3.56195171 2.17944947 1.22474487]

Median per kolom:
[6.  6.  3.  5.5]

Matriks Korelasi antar-kolom:
[[ 1.          0.59731984 -0.95118973  0.        ]
 [ 0.59731984  1.         -0.33813839  0.68768191]
 [-0.95118973 -0.33813839  1.          0.18731716]
 [ 0.          0.68768191  0.18731716  1.        ]]


11. Buatlah array NumPy 1D dengan nilai-nilai dari 0 hingga π dengan interval 
0.1

In [22]:
#definisi nilai π 
pi = np.pi

#Buat array 1D dari 0 hingga pi dengan interval 0.1
array4 = np.arange(0, pi + 0.1, 0.1)

#Menampilkan hasil
print("Array 1D dari 0 hingga π dengan interval 0.1:")
print(array4)

Array 1D dari 0 hingga π dengan interval 0.1:
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2]


12.Hitung nilai sin, cos, dan tan dari setiap elemen array tersebut.	

In [23]:
#Tampilkan array
print("Array 1D dari 0 hingga π dengan interval 0.1:")
print(array4)

#nilai sin,cos dan tan 
sin_value = np.sin(array4)
cos_value = np.cos(array4)
tan_value = np.tan(array4)

#Tampilkan hasil
print("\nNilai sin dari setiap elemen:")
print(sin_value)

print("\nNilai cos dari setiap elemen:")
print(cos_value)

print("\nNilai tan dari setiap elemen:")
print(tan_value)

Array 1D dari 0 hingga π dengan interval 0.1:
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2]

Nilai sin dari setiap elemen:
[ 0.          0.09983342  0.19866933  0.29552021  0.38941834  0.47942554
  0.56464247  0.64421769  0.71735609  0.78332691  0.84147098  0.89120736
  0.93203909  0.96355819  0.98544973  0.99749499  0.9995736   0.99166481
  0.97384763  0.94630009  0.90929743  0.86320937  0.8084964   0.74570521
  0.67546318  0.59847214  0.51550137  0.42737988  0.33498815  0.23924933
  0.14112001  0.04158066 -0.05837414]

Nilai cos dari setiap elemen:
[ 1.          0.99500417  0.98006658  0.95533649  0.92106099  0.87758256
  0.82533561  0.76484219  0.69670671  0.62160997  0.54030231  0.45359612
  0.36235775  0.26749883  0.16996714  0.0707372  -0.02919952 -0.12884449
 -0.22720209 -0.32328957 -0.41614684 -0.5048461  -0.58850112 -0.66627602
 -0.73739372 -0.80114362 -0.85688875 -0.90407214 -0.94222234 -

13. Tampilkan nilai maksimum dan minimum dari hasil perhitungan sin.

In [25]:
#Menghitung nilai max dan minimum sin value
max_sin = np.max(sin_value)
min_sin = np.min(sin_value)

#print hasil
print("\nNilai maksimum dari sin:")
print(max_sin)

print("\nNilai minimum dari sin:")
print(min_sin)


Nilai maksimum dari sin:
0.9995736030415051

Nilai minimum dari sin:
-0.058374143427580086
